### ISSUE TITLE
General questions about usage - 

### ISSUE THREAD

**Issue by wolfejw86** [servicebus/rabbitbus-model-service-template#51]
Is it intentional to not have the service startup in the docker-compose file dependent on a healthcheck? Upon cloning this and running `docker-compose up` the `service` seems to fail to start because rabbit isn't ready yet. I get it's resolved with a quick `docker-compose restart service` however I noticed it does it on subsequent "fresh" `docker-compose up` commands as well. 
I'm mainly just curious as it's not a huge inconvenience, but is it intentional to have to do this or is this scenario maybe not happening on other people's setups out there? Or to just use `restart: always` in the compose config?

My second question is - how would you recommend exposing this data to a UI? I see you have the command API template and this template which feels like an "aggregator" of sorts - would you have a 3rd service connecting to a database aggregating this further which also exposes the data to a UI application? or would you plug some API routes into this service directly that can query against the snapshots?

Thanks for such an awesome boilerplate - I've been enjoying learning all the concepts it ties together from event sourcing to cqrs patterns.

**Comment by patrickleet** [comment]
> re: docker-compose

Usually I have a [meta](https://github.com/mateodelnorte/meta) repository that has a docker-compose file that brings up the whole system, and maps ports to local ports - then the application I'm working on, use VS Code integrated debugger.

> exposing data to a UI

This is intended for use in CQRS, meaning commands and queries are separate. This model is not for queries - instead create a "denormalizer" service which listens for the events about the models changing, and writes projections to a read DB of your choice. 

I've written more about this here: https://hackernoon.com/learning-these-5-microservice-patterns-will-make-you-a-better-engineer-52fc779c470a

Also here: https://hackernoon.com/lessons-ive-learned-building-distributed-systems-with-cqrs-and-event-sourcing-ece284ecc1a1

And here: https://hackernoon.com/complicated-patterns-arent-always-that-complicated-usually-it-s-the-simple-ones-that-bite-you-caf870f2bf03

And Matt has a video worth watching here: https://www.youtube.com/watch?v=4k7bLtqXb8c

**Comment by wolfejw86** [comment]
I see regarding docker-compose and a meta repo - that makes sense.

Regarding the "denormalizer" service - I almost used that word precisely when typing up my questions! (I promise I've already read all 3 of those articles above already and watched that video already as well even if my questions make it sound like I haven't - I'm learning all of these things for the first time so thanks for bearing with me 🤣 )
I think a better version of my question would be - do you have a high(ish) level description of what your denormalizer service would look like in relation to the model and api command services specifically for the todo app? (apologies if i'm butchering the terms). My mind jumps to something like Meteor where you could piggy back off their convenient publishing / minimongo combo but I'm sure there's lots of ways - I'd be curious what you thought :)
Would you have that denormalizer service listen to events that are published from the model service _after_ it has aggregated a snapshot so that it can also aggregate further in an optimal way for the UI? 
Would you use something realtime for publishing changes to the UI or consider a page refresh to be reasonable? (or does it just depend?)
Thanks for the quick response!

**Comment by wolfejw86** [comment]
phenomenal responses - thank you for taking the time. this makes it very clear.  GraphQL is something I haven't gotten into much yet but this sounds like my "excuse" to do so :) 

All of these repos look pretty stable (which is awesome) - is there a list of things that any of them need contributions for? I'm looking for some hacktoberfest picks and if any of these need more documentation or features I'd be interested in contributing as I learn.

Thanks again and have a good one!

**Comment by patrickleet** [comment]
GQL fits in really nicely for querying the read db

This super rough diagram on my instagram might shed a bit of light as well - though commands may not go through the gql - like I said - it's a rough diagram :)

I kinda see gql mutations as an anti-pattern tbh

https://www.instagram.com/p/B3MeM81A6Yr/?igshid=bpotaxpagt8m

**Comment by patrickleet** [comment]
> is there a list of things that any of them need contributions for

yea for sure - better docs, a website for docs even would be great

fwiw I'm in the process of exploring using Knative to do a lot of this instead, which requires Kubernetes experience to understand, but some of the logic should be able to be moved into there - still pretty early on that front though

**Comment by patrickleet** [comment]
some of the middlewares need tests too - many of which are probably pretty simple

**Comment by wolfejw86** [comment]
> yea for sure - better docs, a website for docs even would be great

would you be looking for a package by package website or a website for what I consider the "servicebus package ecosystem" ?  

> fwiw I'm in the process of exploring using Knative to do a lot of this instead, which requires Kubernetes experience to understand, but some of the logic should be able to be moved into there - still pretty early on that front though

Is this mostly in regard to all the helm charts in here? I've heard about Knative but am mostly ignorant of the devops world. It's also something I am slowly trying to skill up, but have mostly focused on writing and dockerizing applications so they're easily compatible with this type of infra - I haven't gotten to provision / deploy / manage the infra myself yet 😅 but I hope to.

> some of the middlewares need tests too - many of which are probably pretty simple

Do you mean like the `express-middleware` and `retry` and `correlate` middleware packages?

**Comment by patrickleet** [comment]
> Is this mostly in regard to all the helm charts in here

No those helm charts in there are to deploy to Kubernetes - they work - the Jenkinsfile is out of date though

> Do you mean like the express-middleware and retry and correlate middleware packages?

yes

> Knative 

Knative is like infrastructure + distributed systems, declaratively. I'm unclear at this point what that will look like, but for example, things like retries and dead-letter queues could be handled by Knative Eventing. We'll still want an abstraction around sending events likely, but that could be an HTTP post to a trigger created by Knative. Need to get further into it. Maybe a `knativebus` and changes to, or a new version of register handlers as they are expected to be in a certain format.

**Comment by wolfejw86** [comment]
Awesome - all good info.  Thank you :)
